services:
  - type: web
    name: nexvault-ctf
    runtime: node
    buildCommand: npm install && npm run build && cd server && npm install
    startCommand: cd server && node index.js
    envVars:
      - key: NODE_VERSION
        value: 20
